export const REPLICATE_FLUX_TRAINER_VERSION =
  "d995297071a44dcb72244e6c19462111649ec86a9646c32df56daa7f14801944";

export const REPLICATE_DEFAULT_TRAINER_MODEL =
  "ostris/flux-dev-lora-trainer";

export const DEFAULT_TRIGGER_WORD_PREFIX = "STORYSPARK";

export const DEFAULT_MODEL_VISIBILITY = "private";

export const DEFAULT_MODEL_DESCRIPTION =
  "Fine-tuned Flux model generated by Story Swap pipeline.";

export const REPLICATE_DEFAULT_HARDWARE = "gpu-h100";



